name: ci_client

on:
  workflow_dispatch:
  push:
    branches:
      - develop
    paths:
      - client

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: client
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v4
        with:
          distribution: corretto
          java-version: 21
      - name: Preparation for ./gradlew
        run: |
          java --version
          chmod u+x ./gradlew
      - name: Set up graphql/server
        working-directory: server
        run: |
          docker build ./ -t todo-graphql
          export ID=`docker run -d -p 4000:4000 todo-graphql`
          docker ps -a
          sleep 10
          docker logs $ID
      - name: spotlessCheck
        run: ./gradlew spotlessCheck
      - name: test
        env:
          SPRING_ACTIVE_PROFILE: ci
        run: ./gradlew test
